/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.QuanLy;

import Models.TaiKhoan;
import Mysql.ConnectSQL;
import javax.swing.JOptionPane;

public class DL_Sua_TaiKhoan extends javax.swing.JDialog {
    ConnectSQL cn = new ConnectSQL();
    /**
     * Creates new form DL_Sua_TaiKhoan
     */
    int ID;
    public DL_Sua_TaiKhoan(java.awt.Frame parent, boolean modal,int id) {
        super(parent, modal);
        initComponents();
        ID = id;
        TaiKhoan b = cn.GetTaiKhoan(id);
        txtTen_04.setText(b.GetUsername());
        txtPass_04.setText(b.GetPassword());
        lblten.setText("Sửa tài khoản - "+b.GetUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOk_04 = new javax.swing.JButton();
        txtPass_04 = new javax.swing.JTextField();
        txtTen_04 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCancer_04 = new javax.swing.JButton();
        lblten = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0), 2));

        btnOk_04.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOk_04.setForeground(new java.awt.Color(51, 0, 51));
        btnOk_04.setText("Xác nhận");
        btnOk_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOk_04ActionPerformed(evt);
            }
        });

        jLabel3.setText("Mật khẩu:");

        btnCancer_04.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancer_04.setForeground(new java.awt.Color(51, 0, 51));
        btnCancer_04.setText("Hủy bỏ");
        btnCancer_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancer_04ActionPerformed(evt);
            }
        });

        lblten.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblten.setText("Sửa tài khoản");

        jLabel2.setText("Tên tài khoản:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnOk_04)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancer_04))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTen_04)
                                    .addComponent(txtPass_04, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(lblten)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblten)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTen_04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass_04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancer_04)
                    .addComponent(btnOk_04))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOk_04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOk_04ActionPerformed
        if(txtTen_04.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Tên tài khoản không được trống !");
            txtTen_04.requestFocus();
            return;
        }
        if(txtPass_04.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Mật khẩu không được trống !");
            txtPass_04.requestFocus();
            return;
        }

        TaiKhoan tk = new TaiKhoan();
        tk.SetID(ID);
        tk.SetUsername(txtTen_04.getText());
        tk.SetPassword(txtPass_04.getText());

        int in = cn.UpdateTK(tk);
        if(in > 0){
            Jp_QLTaiKhoan.tk.FillTable();
            Jp_QLTaiKhoan.tk.updateUI();

            this.dispose();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnOk_04ActionPerformed

    private void btnCancer_04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancer_04ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancer_04ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancer_04;
    private javax.swing.JButton btnOk_04;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblten;
    private javax.swing.JTextField txtPass_04;
    private javax.swing.JTextField txtTen_04;
    // End of variables declaration//GEN-END:variables
}
