/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.QuanLy;

public class JpQuanLy extends javax.swing.JPanel {

    /**
     * Creates new form JpQuanLy
     */
    public JpQuanLy() {
        initComponents();
        LoadPanel(2);
    }

    Jp_QLThucDon td;
    Jp_QLNhomMon nm;
    Jp_QLTaiKhoan nv;
    public void LoadPanel(int i){
        jpql.removeAll();
        switch (i){  
            case 2:
                if(td == null){
                    td = new Jp_QLThucDon();
                }
                jpql.add(td);                
                break;
            case 3:
                if(nm == null){
                    nm = new Jp_QLNhomMon();
                }
                jpql.add(nm);                
                break; 
            case 4:
                if(nv == null){
                    nv = new Jp_QLTaiKhoan();
                }
                jpql.add(nv);                
                break;                
            default:
                break;
                
        }
        jpql.updateUI();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnMon_01 = new javax.swing.JButton();
        btnThucDon_01 = new javax.swing.JButton();
        btnUser_01 = new javax.swing.JButton();
        jpql = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(1051, 486));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnMon_01.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnMon_01.setForeground(new java.awt.Color(51, 51, 0));
        btnMon_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/kiemke.png"))); // NOI18N
        btnMon_01.setText("QUẢN LÝ NHÓM MÓN");
        btnMon_01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMon_01.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnMon_01.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMon_01.setIconTextGap(10);
        btnMon_01.setPreferredSize(new java.awt.Dimension(0, 35));
        btnMon_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMon_01ActionPerformed(evt);
            }
        });

        btnThucDon_01.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnThucDon_01.setForeground(new java.awt.Color(51, 51, 0));
        btnThucDon_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/mailinglist.jpg"))); // NOI18N
        btnThucDon_01.setText("QUẢN LÝ THỰC ĐƠN");
        btnThucDon_01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThucDon_01.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnThucDon_01.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThucDon_01.setIconTextGap(10);
        btnThucDon_01.setPreferredSize(new java.awt.Dimension(0, 35));
        btnThucDon_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThucDon_01ActionPerformed(evt);
            }
        });

        btnUser_01.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnUser_01.setForeground(new java.awt.Color(51, 51, 0));
        btnUser_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/qluser.png"))); // NOI18N
        btnUser_01.setText("QUẢN LÝ TÀI KHOẢN");
        btnUser_01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUser_01.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnUser_01.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUser_01.setIconTextGap(10);
        btnUser_01.setPreferredSize(new java.awt.Dimension(0, 35));
        btnUser_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUser_01ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThucDon_01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMon_01, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(btnUser_01, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThucDon_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMon_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUser_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpql.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpql, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpql, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThucDon_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThucDon_01ActionPerformed
        LoadPanel(2);// TODO add your handling code here:
    }//GEN-LAST:event_btnThucDon_01ActionPerformed

    private void btnMon_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMon_01ActionPerformed
        LoadPanel(3);// TODO add your handling code here:
    }//GEN-LAST:event_btnMon_01ActionPerformed

    private void btnUser_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUser_01ActionPerformed
        LoadPanel(4);  // TODO add your handling code here:
    }//GEN-LAST:event_btnUser_01ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMon_01;
    private javax.swing.JButton btnThucDon_01;
    private javax.swing.JButton btnUser_01;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jpql;
    // End of variables declaration//GEN-END:variables
}
