/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Interface.BanHang.jpBanHang;
import Interface.Home.JpHome;
import Interface.QuanLy.JpQuanLy;
import Interface.Setting.JpSetting;
import Models.Ban;
import Models.TaiKhoan;
import Mysql.ConnectSQL;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;
import Interface.ThongKe.JpThongKe;

public final class frmMain extends javax.swing.JFrame {
    ConnectSQL cn = new ConnectSQL();
    /**
     * Creates new form frmMain
     */
    public TaiKhoan loadtaikhoan(String user, String pass){
       return cn.GetTaiKhoan(user, pass);       
    }    
    public frmMain() {
        initComponents();
        fill();
        Clock clock= new Clock(); 
        clock.start(); 
        txtqtv_01.setText(Run.tk.GetUsername());
       
    }
    SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss_a");
    public class Clock extends Thread{ 
    public Clock(){    } 
    @Override
    public void run(){ 
        while(true){ 
            int bandat =0, banpv=0;
            ArrayList<Ban> arrBan = cn.GetBan(0);
            for(int i = 0;i<arrBan.size();i++){
                if(arrBan.get(i).GetTrangThai().equals("Đang phục vụ")){
                    banpv++;
                }
                if(arrBan.get(i).GetTrangThai().equals("Đã đặt trước")){
                    bandat++;
                }            
            } 
            lblpv_01.setText(+banpv+" bàn đang phục vụ");
            lbldat_01.setText(+bandat+" bàn đặt trước");
            Calendar calendar = Calendar.getInstance();                
            String str;  
            str= sdf.format(calendar.getTime()); 
            lbltime_01.setText(str); 
        try{ 
            sleep(1000); 
          } catch(Exception e){ 
             System.out.println(e); 
            } 
      } 
    }
    }
    public void fill(){
        home = new JpHome();
        jpLayout.add(home);
        jpLayout.updateUI();
        //Khai bao dinh dang ngay thang
        
      
    }
    jpBanHang banhang;
    JpHome home ;
    JpSetting Set;
    JpQuanLy ql;
    JpThongKe tk ;
    public void reloadPanel(int i) {
        jpLayout.removeAll();
        switch (i) {
            case 1:
                if (banhang == null) {
                    banhang = new jpBanHang();
                } 
                btnBanHang_01.setPressedIcon(new ImageIcon("down.png"));
                jpLayout.add(banhang);
                break;
            case 2:
                if (home == null) {
                    home = new JpHome();
                }
                btnTrangChu_01.setPressedIcon(new ImageIcon("down.png"));
                jpLayout.add(home);
                break;
            case 3:
                if(ql == null){
                    ql = new JpQuanLy();
                }
                btnQuanLy_01.setPressedIcon(new ImageIcon("down.png"));
                jpLayout.add(ql);
                break;
            case 4:
                tk = new JpThongKe();
                
                btnThongKe_01.setPressedIcon(new ImageIcon("down.png"));
                jpLayout.add(tk);
                break;
            case 6:
                if (Set == null) {
                    Set = new JpSetting();
                } 
                btnThietLap_01.setPressedIcon(new ImageIcon("down.png"));
                jpLayout.add(Set);
                break;                
            default:
                break;
        }
        jpLayout.updateUI();
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel2 = new javax.swing.JPanel();
        btnThietLap_01 = new javax.swing.JButton();
        btnQuanLy_01 = new javax.swing.JButton();
        btnBanHang_01 = new javax.swing.JButton();
        btnThongKe_01 = new javax.swing.JButton();
        jpLayout = new javax.swing.JPanel();
        btnthoat_01 = new javax.swing.JButton();
        btnTrangChu_01 = new javax.swing.JButton();
        lbltime_01 = new javax.swing.JLabel();
        lblpv_01 = new javax.swing.JLabel();
        lbldat_01 = new javax.swing.JLabel();
        txtqtv_01 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trung Hòa Coffee Music");
        setBackground(Color.decode("#e6e6e6")
        );
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setForeground(new java.awt.Color(255, 204, 255));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel2.setBackground(Color.decode("#e6e6e6"));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 0), 2));
        jPanel2.setPreferredSize(new java.awt.Dimension(1280, 600));

        btnThietLap_01.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThietLap_01.setForeground(new java.awt.Color(51, 51, 51));
        btnThietLap_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/Settings-L-icon.png"))); // NOI18N
        btnThietLap_01.setText("THIẾT LẬP");
        btnThietLap_01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThietLap_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThietLap_01ActionPerformed(evt);
            }
        });

        btnQuanLy_01.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnQuanLy_01.setForeground(new java.awt.Color(51, 51, 51));
        btnQuanLy_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/icon-hoc-nau-an-Huong-nghiep-a-au-2015.png"))); // NOI18N
        btnQuanLy_01.setText("QUẢN LÝ");
        btnQuanLy_01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuanLy_01.setPreferredSize(new java.awt.Dimension(140, 49));
        btnQuanLy_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLy_01ActionPerformed(evt);
            }
        });

        btnBanHang_01.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBanHang_01.setForeground(new java.awt.Color(51, 51, 51));
        btnBanHang_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/sellicon.png"))); // NOI18N
        btnBanHang_01.setText("BÁN HÀNG");
        btnBanHang_01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBanHang_01.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnBanHang_01.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBanHang_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHang_01ActionPerformed(evt);
            }
        });

        btnThongKe_01.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThongKe_01.setForeground(new java.awt.Color(51, 51, 51));
        btnThongKe_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/thongke.png"))); // NOI18N
        btnThongKe_01.setText("THỐNG KÊ");
        btnThongKe_01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThongKe_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKe_01ActionPerformed(evt);
            }
        });

        jpLayout.setBackground(Color.decode("#e6e6e6")
        );
        jpLayout.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 0), new java.awt.Color(0, 51, 51)));
        jpLayout.setLayout(new java.awt.BorderLayout());

        btnthoat_01.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        btnthoat_01.setForeground(new java.awt.Color(0, 51, 0));
        btnthoat_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/Logout.png"))); // NOI18N
        btnthoat_01.setText("Đăng xuất");
        btnthoat_01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnthoat_01.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnthoat_01.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnthoat_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoat_01ActionPerformed(evt);
            }
        });

        btnTrangChu_01.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTrangChu_01.setForeground(new java.awt.Color(51, 51, 51));
        btnTrangChu_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/HOME.png"))); // NOI18N
        btnTrangChu_01.setText("TRANG CHỦ");
        btnTrangChu_01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrangChu_01.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnTrangChu_01.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnTrangChu_01.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnTrangChu_01FocusGained(evt);
            }
        });
        btnTrangChu_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrangChu_01MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrangChu_01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrangChu_01MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTrangChu_01MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnTrangChu_01MouseReleased(evt);
            }
        });
        btnTrangChu_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChu_01ActionPerformed(evt);
            }
        });

        lbltime_01.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbltime_01.setForeground(new java.awt.Color(51, 102, 0));
        lbltime_01.setText("jLabel1");

        lblpv_01.setForeground(new java.awt.Color(94, 94, 21));
        lblpv_01.setText("jLabel1");

        lbldat_01.setForeground(new java.awt.Color(94, 94, 21));
        lbldat_01.setText("jLabel1");

        txtqtv_01.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtqtv_01.setForeground(new java.awt.Color(204, 0, 0));
        txtqtv_01.setText("jLabel1");

        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setText("QTV:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTrangChu_01)
                        .addGap(18, 18, 18)
                        .addComponent(btnBanHang_01)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuanLy_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThongKe_01)
                        .addGap(18, 18, 18)
                        .addComponent(btnThietLap_01)
                        .addGap(171, 171, 171)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltime_01)
                            .addComponent(lbldat_01)
                            .addComponent(lblpv_01))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtqtv_01))
                            .addComponent(btnthoat_01)))
                    .addComponent(jpLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnQuanLy_01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBanHang_01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTrangChu_01))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(lbldat_01)
                            .addGap(3, 3, 3))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThongKe_01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThietLap_01)
                            .addComponent(lblpv_01)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtqtv_01)
                            .addComponent(lbltime_01)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnthoat_01)))
                .addGap(8, 8, 8)
                .addComponent(jpLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1241, 1241, 1241)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBanHang_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHang_01ActionPerformed
        reloadPanel(1);
    }//GEN-LAST:event_btnBanHang_01ActionPerformed
    public void thoat()
    {
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE );
        int kq=JOptionPane.showConfirmDialog(null, "Bạn có muốn đóng phần mềm ?","FBI Warning",JOptionPane.YES_NO_OPTION);
        if(kq==0)
        {
        System.exit(0);
       }
}
    private void btnthoat_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoat_01ActionPerformed
        // TODO add your handling code here:
        int kq=JOptionPane.showConfirmDialog(null, "Đăng xuất khỏi tài khoản " +Run.tk.GetUsername()+ "?","FBI Warning",JOptionPane.YES_NO_OPTION);
        if(kq==0)
        {
            Run.frmlg.setVisible(true);
            Run.frmlg.thoat();
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_btnthoat_01ActionPerformed

    private void btnTrangChu_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChu_01ActionPerformed
        // TODO add your handling code here:
        reloadPanel(2);
    }//GEN-LAST:event_btnTrangChu_01ActionPerformed

    private void btnThietLap_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThietLap_01ActionPerformed
        // TODO add your handling code here:
        reloadPanel(6);
    }//GEN-LAST:event_btnThietLap_01ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void btnThongKe_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKe_01ActionPerformed
        reloadPanel(4);
//        this.dispose();
//        Run.rerun();
    }//GEN-LAST:event_btnThongKe_01ActionPerformed

    private void btnTrangChu_01FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnTrangChu_01FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnTrangChu_01FocusGained

    private void btnTrangChu_01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChu_01MouseClicked
               // TODO add your handling code here:
                
    }//GEN-LAST:event_btnTrangChu_01MouseClicked

    private void btnTrangChu_01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChu_01MouseEntered
              // TODO add your handling code here:
               
    }//GEN-LAST:event_btnTrangChu_01MouseEntered

    private void btnTrangChu_01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChu_01MouseExited
        // TODO add your handling code here:
         
    }//GEN-LAST:event_btnTrangChu_01MouseExited

    private void btnTrangChu_01MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChu_01MouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnTrangChu_01MouseReleased

    private void btnTrangChu_01MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChu_01MousePressed
        
    }//GEN-LAST:event_btnTrangChu_01MousePressed
    
    private void btnQuanLy_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLy_01ActionPerformed
        // TODO add your handling code here:
        
        reloadPanel(3);
        
    }//GEN-LAST:event_btnQuanLy_01ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanHang_01;
    private javax.swing.JButton btnQuanLy_01;
    private javax.swing.JButton btnThietLap_01;
    private javax.swing.JButton btnThongKe_01;
    private javax.swing.JButton btnTrangChu_01;
    private javax.swing.JButton btnthoat_01;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpLayout;
    private javax.swing.JLabel lbldat_01;
    private javax.swing.JLabel lblpv_01;
    private javax.swing.JLabel lbltime_01;
    private javax.swing.JLabel txtqtv_01;
    // End of variables declaration//GEN-END:variables
}
